<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <LightD3D12EnableAssimp>true</LightD3D12EnableAssimp>
    <VcpkgTriplet Condition="'$(VcpkgTriplet)'==''">x64-windows</VcpkgTriplet>
    <VcpkgEnableManifest Condition="'$(VcpkgEnableManifest)'==''">true</VcpkgEnableManifest>
    <VcpkgManifestRoot Condition="'$(VcpkgManifestRoot)'==''">$(MSBuildThisFileDirectory)</VcpkgManifestRoot>
    <VcpkgRoot Condition="'$(VcpkgRoot)'=='' and Exists('$(MSBuildThisFileDirectory)third_party\vcpkg\vcpkg.exe')">$(MSBuildThisFileDirectory)third_party\vcpkg\</VcpkgRoot>
    <VcpkgRoot Condition="'$(VcpkgRoot)'=='' and '$(VCPKG_ROOT)'!=''">$(VCPKG_ROOT)</VcpkgRoot>
    <VcpkgRoot Condition="'$(VcpkgRoot)'!='' and !HasTrailingSlash('$(VcpkgRoot)')">$(VcpkgRoot)\</VcpkgRoot>
    <VcpkgInstalledDir Condition="'$(VcpkgInstalledDir)'=='' and Exists('$(MSBuildThisFileDirectory)vcpkg_installed\$(VcpkgTriplet)\')">$(MSBuildThisFileDirectory)vcpkg_installed\$(VcpkgTriplet)\</VcpkgInstalledDir>
    <VcpkgInstalledDir Condition="'$(VcpkgInstalledDir)'=='' and '$(VcpkgRoot)'!='' and Exists('$(VcpkgRoot)installed\$(VcpkgTriplet)\')">$(VcpkgRoot)installed\$(VcpkgTriplet)\</VcpkgInstalledDir>
  </PropertyGroup>
</Project>
